//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1008
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication2.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   指定された比較元ファイルが存在しません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_FILE1_NOT_EXISTS {
            get {
                return ResourceManager.GetString("MSG_FILE1_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された比較先ファイルが存在しません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_FILE2_NOT_EXISTS {
            get {
                return ResourceManager.GetString("MSG_FILE2_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   比較元ファイルを指定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_INPUT_FILE1 {
            get {
                return ResourceManager.GetString("MSG_INPUT_FILE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   比較先ファイルを指定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_INPUT_FILE2 {
            get {
                return ResourceManager.GetString("MSG_INPUT_FILE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チェック項目表が空になっています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_ITEM_TABLE_EMPTY {
            get {
                return ResourceManager.GetString("MSG_ITEM_TABLE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チェック項目表入力不足！行：{0}、列：{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MSG_ITEM_TABLE_MISS {
            get {
                return ResourceManager.GetString("MSG_ITEM_TABLE_MISS", resourceCulture);
            }
        }
    }
}
